In [1]:
# Import relevant libraries
from splinter import Browser
from bs4 import BeautifulSoup as soup
from webdriver_manager.chrome import ChromeDriverManager
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt

In [2]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

In [3]:
url = "https://www.cdc.gov/flu/prevent/vaccinesupply-2011.htm"
browser.visit(url)

In [4]:
# Create a Beautiful Soup Object
soup = soup(browser.html, 'html.parser')

In [5]:
# Extract all rows of data
results = soup.find_all('table', class_= 'table')

In [6]:
# Create an empty list
collection = []

# Loop through the scraped data to create a list of rows
for i in results:
    j = i.find_all('h2')
    row = [item.text for item in j]
    collection.append(row)

In [7]:
# Create a Pandas DataFrame by using the list of rows and a list of the column names
tables = pd.read_html(url)
vaccines = tables[0]
vaccines

               Week Total Doses Distributed
0          02/03/12   ≈ 132.1 million doses
1          01/20/12   ≈ 132.0 million doses
2          12/30/11   ≈ 131.2 million doses
3          12/16/11   ≈ 130.6 million doses
4           12/9/11   ≈ 130.1 million doses
5          11/25/11   ≈ 129.2 million doses
6          11/18/11   ≈ 127.9 million doses
7          11/11/11   ≈ 126.9 million doses
8          10/28/11   ≈ 124.9 million doses
9          10/21/11   ≈ 122.9 million doses
10         10/07/11   ≈ 115.5 million doses
11          9/30/11   ≈ 110.4 million doses
12          9/23/11   ≈ 104.8 million doses
13          9/16/11    ≈ 97.7 million doses
14          9/09/11    ≈ 85.9 million doses
15          9/02/11    ≈ 67.9 million doses
16          8/26/11    ≈ 55.1 million doses
17  ≈ = approximate         ≈ = approximate

In [8]:
# Confirm DataFrame was created successfully
vaccines.to_csv("Resource/vaccines2011.csv",index=False)

In [9]:
allYearsVaccine = pd.concat(map(pd.read_csv, ['Resource/vaccines2011.csv', 'Resource/vaccines2012.csv', 'Resource/vaccines2013.csv', 'Resource/vaccines2014.csv', 'Resource/vaccines2015.csv', 'Resource/vaccines2016.csv', 'Resource/vaccines2017.csv', 'Resource/vaccines2018.csv', 'Resource/vaccines2020.csv', 'Resource/vaccines2021.csv']))
allYearsVaccine

         Week Total Doses Distributed
0    02/03/12   ≈ 132.1 million doses
1    01/20/12   ≈ 132.0 million doses
2    12/30/11   ≈ 131.2 million doses
3    12/16/11   ≈ 130.6 million doses
4     12/9/11   ≈ 130.1 million doses
..        ...                     ...
21  9/24/2021                 100.8 M
22  9/17/2021                  84.8 M
23  9/10/2021                  66.8 M
24   9/3/2021                  53.2 M
25  8/14/2020                  13.7 M

[206 rows x 2 columns]